"""add_fks_to_photos_and_mapping

Revision ID: 263de27c0a92
Revises: 838c997c73e7
Create Date: 2026-07-23 10:35:30.170911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263de27c0a92'
down_revision: Union[str, None] = '838c997c73e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create indexes and foreign keys for device_person_mapping
    op.create_index(op.f('ix_device_person_mapping_device_id'), 'device_person_mapping', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_person_mapping_person_id_internal'), 'device_person_mapping', ['person_id_internal'], unique=False)
    op.create_foreign_key('fk_device_person_mapping_person_id', 'device_person_mapping', 'personnel', ['person_id_internal'], ['person_id_internal'], ondelete='CASCADE')
    op.create_foreign_key('fk_device_person_mapping_device_id', 'device_person_mapping', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    
    # Create indexes and foreign keys for photo_registrations
    op.create_index(op.f('ix_photo_registrations_device_id'), 'photo_registrations', ['device_id'], unique=False)
    op.create_index(op.f('ix_photo_registrations_person_id_internal'), 'photo_registrations', ['person_id_internal'], unique=False)
    op.create_foreign_key('fk_photo_registrations_person_id', 'photo_registrations', 'personnel', ['person_id_internal'], ['person_id_internal'], ondelete='CASCADE')
    op.create_foreign_key('fk_photo_registrations_device_id', 'photo_registrations', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign keys and indexes for photo_registrations
    op.drop_constraint('fk_photo_registrations_device_id', 'photo_registrations', type_='foreignkey')
    op.drop_constraint('fk_photo_registrations_person_id', 'photo_registrations', type_='foreignkey')
    op.drop_index(op.f('ix_photo_registrations_person_id_internal'), table_name='photo_registrations')
    op.drop_index(op.f('ix_photo_registrations_device_id'), table_name='photo_registrations')
    
    # Drop foreign keys and indexes for device_person_mapping
    op.drop_constraint('fk_device_person_mapping_device_id', 'device_person_mapping', type_='foreignkey')
    op.drop_constraint('fk_device_person_mapping_person_id', 'device_person_mapping', type_='foreignkey')
    op.drop_index(op.f('ix_device_person_mapping_person_id_internal'), table_name='device_person_mapping')
    op.drop_index(op.f('ix_device_person_mapping_device_id'), table_name='device_person_mapping')
    # ### end Alembic commands ###
