"""add location and unit master data tables

Revision ID: 29531400f0e7
Revises: 1c0692501cfd
Create Date: 2026-07-20 08:41:32.105917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29531400f0e7'
down_revision: Union[str, None] = '1c0692501cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('type', sa.Enum('FORCE', 'COMMAND', 'BATTALION', 'UNIT', name='unittype'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'code', name='uq_units_parent_code')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('authority_unit_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authority_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('profile_mod_requests')
    op.add_column('devices', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(None, 'devices', 'units', ['unit_id'], ['id'])
    op.drop_column('devices', 'location')
    op.drop_column('profiles', 'profile_mod_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_mod_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'unit_id')
    op.drop_column('devices', 'location_id')
    op.create_table('profile_mod_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mobile_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ext_no', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_mod_requests_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('profile_mod_requests_pkey'))
    )
    op.drop_table('locations')
    op.drop_table('units')
    # ### end Alembic commands ###
