"""change device location to foreign key

Revision ID: 5a35db8d8ed5
Revises: 50f6ed33ec34
Create Date: 2026-07-21 13:09:22.838736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a35db8d8ed5'
down_revision: Union[str, None] = '50f6ed33ec34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'locations', ['location_id'], ['id'])
    op.drop_column('devices', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'location_id')
    # ### end Alembic commands ###
