import { useI18n } from '../../../infra/locales/I18nContext'
import { useDashboardStore } from '../store'
import type { ExceptionResult } from '../types'
import { formatDateTime, formatNumber } from '../utils'

export default function AttendanceExceptionsTable({ data }: { data: ExceptionResult }) {
  const { t, lang } = useI18n(); const setPage = useDashboardStore((s) => s.setExceptionPage); const setPageSize = useDashboardStore((s) => s.setExceptionPageSize)
  const { page, pages, page_size } = data.meta
  return <><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-surface-2 text-secondary"><tr>{(['date','time','employee','employeeNo','organization','device'] as const).map(h=><th scope="col" key={h} className="px-3 py-3 text-start font-medium">{t(`nav.dashboard.exceptions.${h}` as any)}</th>)}</tr></thead><tbody>{data.items.map(item=><tr key={`${item.org_id ?? ''}:${item.id}`} className="border-t border-bd"><td className="px-3 py-3">{formatDateTime(item.report_date,lang,'date')}</td><td className="px-3 py-3">{formatDateTime(item.clock_time,lang,'time')}</td><td className="px-3 py-3">{item.person_name ?? item.person_no ?? t('nav.dashboard.exceptions.unknown')}</td><td className="px-3 py-3">{item.person_no ?? '—'}</td><td className="px-3 py-3">{item.org_id ?? '—'}</td><td className="px-3 py-3">{item.device_name ?? item.device_key ?? '—'}</td></tr>)}</tbody></table></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm"><label>{t('nav.dashboard.exceptions.pageSize')}<select className="ms-2 min-h-10 rounded-lg border border-bd bg-surface-2 px-2" value={page_size} onChange={(e)=>void setPageSize(Number(e.target.value))}>{[10,20,50].map(x=><option key={x}>{x}</option>)}</select></label><div className="flex items-center gap-2"><button aria-label={t('nav.dashboard.actions.previous')} disabled={page<=1} onClick={()=>void setPage(page-1)} className="min-h-10 rounded-lg border border-bd px-3 disabled:opacity-40">{t('nav.dashboard.actions.previous')}</button><span>{formatNumber(page,lang)} / {formatNumber(Math.max(pages,1),lang)}</span><button aria-label={t('nav.dashboard.actions.next')} disabled={page>=pages} onClick={()=>void setPage(page+1)} className="min-h-10 rounded-lg border border-bd px-3 disabled:opacity-40">{t('nav.dashboard.actions.next')}</button></div></div></>
}
